apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u9rn2okif-java-springboot
  janus-idp.io/tekton: u9rn2okif-java-springboot
  backstage.io/kubernetes-id: u9rn2okif-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u9rn2okif-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
